objects/Account.object
<CustomObject><fields>
        <fullName>Chapter_Number__c</fullName>
        <inlineHelpText>{AA000}</inlineHelpText>
        <label>Chapter Number</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Facebook_Page__c</fullName>
        <label>Facebook Page</label>
        <type>Url</type>
    </fields><fields>
        <fullName>Regional_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional Director</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Regional Director)</relationshipLabel>
        <relationshipName>Chapters</relationshipName>
        <type>Lookup</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWrite</sharingModel><recordTypes>
        <fullName>Chapter</fullName>
        <active>true</active>
        <description>A group of Delta Waterfowl members.</description>
        <label>Chapter</label>
    </recordTypes></CustomObject>

classes/ChapterController.cls
global with sharing class ChapterController {
	@RemoteAction
	global static List<Account> getChapters() {
		List<Account> accountsByChapters = [select Id, Name, Type,
		Regional_Director__r.Name, Chapter_Number__c, Website, Facebook_Page__c,
		BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry,
		BillingLatitude, BillingLongitude from Account where RecordType.Name = 'Chapter'];
		return accountsByChapters;
	}
}