objects/Benefit__c.object
<CustomObject><fields>
        <fullName>Count__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Count</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Total_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unit Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Unit_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unit Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>false</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>false</enableSharing><enableStreamingApi>false</enableStreamingApi><label>Benefit</label><nameField>
        <label>Benefit Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Benefits</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Opportunity.object
<CustomObject><fields>
        <fullName>Benefit_Stats__c</fullName>
        <label>Benefit Stats</label>
        <type>TextArea</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Opportunity_Benefit__c.object
<CustomObject><fields>
        <fullName>Benefit__c</fullName>
        <label>Benefit</label>
        <referenceTo>Benefit__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunity_Benefits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Benefits</relationshipLabel>
        <relationshipName>Benefits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Total_Value__c</fullName>
        <label>Total Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>false</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>false</enableSharing><enableStreamingApi>false</enableStreamingApi><label>Opportunity Benefit</label><nameField>
        <displayFormat>OB-{0000}</displayFormat>
        <label>Opportunity Benefit Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Opportunity Benefits</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/OpportunityBenefitService_Test.cls
@isTest
private class OpportunityBenefitService_Test {
  @isTest
  static void testSetBenefitStats() {
    Benefit__c b1 = new Benefit__c();
    b1.Name = 'Benefit 1';
    b1.Count__c = 1;
    b1.Total_Value__c = 1;
    b1.Unit_Cost__c = 1;
    insert b1;

    Benefit__c b2 = new Benefit__c();
    b2.Name = 'Benefit 2';
    b2.Count__c = 2;
    b2.Total_Value__c = 2;
    b2.Unit_Cost__c = 2;
    insert b2;

    Benefit__c b3 = new Benefit__c();
    b3.Name = 'Magazine';
    b3.Count__c = 2;
    b3.Total_Value__c = 2;
    b3.Unit_Cost__c = 2;
    insert b3;

    Opportunity opp = new Opportunity();
    opp.name = 'Test Opp 1';
    opp.StageName = 'Closed Won - 100%';
    opp.CloseDate = Date.today();
    insert opp;

    Opportunity_Benefit__c ben1 = new Opportunity_Benefit__c();
    ben1.Opportunity__c = opp.id;
    ben1.Benefit__c = b1.id;
    ben1.Count__c = 1;

    Opportunity_Benefit__c ben2 = new Opportunity_Benefit__c();
    ben2.Opportunity__c = opp.id;
    ben2.Benefit__c = b2.id;
    ben2.Count__c = 2;

    Opportunity_Benefit__c ben3 = new Opportunity_Benefit__c();
    ben3.Opportunity__c = opp.id;
    ben3.Benefit__c = b3.id;
    ben3.Count__c = 2;

    List<Opportunity_Benefit__c> bens = new List<Opportunity_Benefit__c>();
    bens.add(ben1);
    bens.add(ben2);
    bens.add(ben3);

    Test.StartTest();
    insert bens;
    Test.StopTest();

    Opportunity selectedOpp = [select id, Benefit_Stats__c from Opportunity where id =: opp.id];
    System.assertEquals('Benefit 1 - 1, Benefit 2 - 2', selectedOpp.Benefit_Stats__c);
  }

  @isTest
  static void testDeleteSetBenefitStats() {
    Benefit__c b1 = new Benefit__c();
    b1.Name = 'Benefit 1';
    b1.Count__c = 1;
    b1.Total_Value__c = 1;
    b1.Unit_Cost__c = 1;
    insert b1;

    Benefit__c b2 = new Benefit__c();
    b2.Name = 'Benefit 2';
    b2.Count__c = 2;
    b2.Total_Value__c = 2;
    b2.Unit_Cost__c = 2;
    insert b2;

    Opportunity opp = new Opportunity();
    opp.name = 'Test Opp 1';
    opp.StageName = 'Closed Won - 100%';
    opp.CloseDate = Date.today();
    insert opp;

    Opportunity_Benefit__c ben1 = new Opportunity_Benefit__c();
    ben1.Opportunity__c = opp.id;
    ben1.Benefit__c = b1.id;
    ben1.Count__c = 1;

    Opportunity_Benefit__c ben2 = new Opportunity_Benefit__c();
    ben2.Opportunity__c = opp.id;
    ben2.Benefit__c = b2.id;
    ben2.Count__c = 2;

    List<Opportunity_Benefit__c> bens = new List<Opportunity_Benefit__c>();
    bens.add(ben1);
    bens.add(ben2);

    insert bens;
    Test.StartTest();
    delete ben1;
    Test.StopTest();

    Opportunity selectedOpp = [select id, Benefit_Stats__c from Opportunity where id =: opp.id];
    System.assertEquals('Benefit 2 - 2', selectedOpp.Benefit_Stats__c);
  }
}