objects/Benefit__c.object
<CustomObject><fields>
        <fullName>Count__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Count</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>false</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>false</enableSharing><enableStreamingApi>false</enableStreamingApi><label>Benefit</label><nameField>
        <label>Benefit Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Benefits</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Opportunity.object
<CustomObject><fields>
        <fullName>Benefit_Stats__c</fullName>
        <label>Benefit Stats</label>
        <type>TextArea</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Opportunity_Benefit__c.object
<CustomObject><fields>
        <fullName>Benefit__c</fullName>
        <label>Benefit</label>
        <referenceTo>Benefit__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunity_Benefits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Benefits</relationshipLabel>
        <relationshipName>Benefits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>false</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>false</enableSharing><enableStreamingApi>false</enableStreamingApi><label>Opportunity Benefit</label><nameField>
        <displayFormat>OB-{0000}</displayFormat>
        <label>Opportunity Benefit Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Opportunity Benefits</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/OpportunityBenefitService.cls
public without sharing class OpportunityBenefitService {
  public static void setBenefitStats(List<Opportunity_Benefit__c> benefitList) {
    Set<Id> oppIds = new Set<Id>();
    for(Opportunity_Benefit__c oppBenefit : benefitList) {
      oppIds.add(oppBenefit.Opportunity__c);
    }
    List<Opportunity> opps = [Select id, Benefit_Stats__c, (Select id, Benefit__r.Name, Count__c from Benefits__r where Benefit__r.Name != 'Magazine' AND Benefit__r.Name != 'Decal') from Opportunity where id in :oppIds];

    for(Opportunity opp : opps) {
      String[] parts = new List<String>();
      for (Opportunity_Benefit__c oppBenefit : opp.Benefits__r) {
        String val = oppBenefit.Benefit__r.Name + ' - ' + oppBenefit.Count__c;
        if (String.join(parts, ', ').length() + val.length() > 200) {
          break;
        }
        parts.add(val);
      }
      opp.Benefit_Stats__c = String.join(parts, ', ');
    }
    update opps;
  }
}