objects/Campaign.object
<CustomObject><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <inlineHelpText>City, State</inlineHelpText>
        <label>Location City, State</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><sharingModel>FullAccess</sharingModel><recordTypes>
        <fullName>List</fullName>
        <active>true</active>
        <label>List</label>
    </recordTypes><recordTypes>
        <fullName>Void</fullName>
        <active>false</active>
        <description>Tickets are sold to a group of people in order to win something</description>
        <label>Void</label>
    </recordTypes></CustomObject>

classes/EventsByDateController_Test.cls
@isTest
private class EventsByDateController_Test {
  static testMethod void EventsByDateController() {

    Campaign c1 = new Campaign();

    c1.Name = 'Jeff';
    c1.StartDate = Date.today();
    c1.EndDate = Date.today();
    c1.Location__c = 'Here';
    c1.Start_Time__c = Datetime.now();
    c1.End_Time__c = Datetime.now();
    insert c1;

    Test.StartTest();
    List<Campaign> returnData = EventsByDate_Controller.getEventDetails();
    system.assertNotEquals(returnData.size(), 1);
    Test.StopTest();
  }
}