objects/Campaign.object
<CustomObject><fields>
        <fullName>Default_Letter_Code__c</fullName>
        <label>Default Letter Code</label>
        <picklist>
            <picklistValues>
                <fullName>Calendar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada Sweepstakes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committee Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donation Calendar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ducks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Volunteer Raffle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Hunt Mem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Donation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gratis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hunters Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sportsman’s Raffle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spring Raffle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Truck Raffle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waterfowl ID Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>We do ours Seperate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Winter Raffle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Year End</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Default_Market_Code__c</fullName>
        <label>Default Market Code</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Landing_Page_URL__c</fullName>
        <label>Landing Page URL</label>
        <type>Url</type>
    </fields><fields>
        <fullName>Primary_Department__c</fullName>
        <globalPicklist>Departments</globalPicklist>
        <label>Primary Department</label>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Primary_GAU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary GAU</label>
        <referenceTo>npsp__General_Accounting_Unit__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><sharingModel>FullAccess</sharingModel><recordTypes>
        <fullName>List</fullName>
        <active>true</active>
        <label>List</label>
    </recordTypes><recordTypes>
        <fullName>Void</fullName>
        <active>false</active>
        <description>Tickets are sold to a group of people in order to win something</description>
        <label>Void</label>
    </recordTypes></CustomObject>

classes/CampaignService_Test.cls
@isTest
private class CampaignService_Test {

  @isTest
  static void testSetParentDefaults() {
    npsp__General_Accounting_Unit__c gau = new npsp__General_Accounting_Unit__c();
    gau.name = 'Test GAU';
    insert gau;

    Campaign parentCamp = new Campaign();
    parentCamp.name = 'Parent';
    parentCamp.Landing_Page_URL__c = 'http://www.google.com';
    parentCamp.Primary_Department__c = 'DEV';
    parentCamp.Primary_GAU__c = gau.id;
    parentCamp.Default_Letter_Code__c = 'Mem';
    parentCamp.Default_Market_Code__c = 'foo';
    parentCamp.StartDate = Date.newInstance(2016, 8, 3);
    parentCamp.EndDate = Date.newInstance(2016, 8, 3);
    insert parentcamp;

    Campaign childCamp = new Campaign();
    childCamp.name = 'Child';
    childCamp.parentId = parentCamp.id;

    Test.StartTest();
    insert childCamp;
    Test.StopTest();

    Campaign selectedCamp = [Select id, Landing_Page_URL__c, Primary_Department__c, Primary_GAU__c, Default_Letter_Code__c, Default_Market_Code__c, StartDate, EndDate from campaign where id =: childCamp.id][0];
    System.assertEquals(selectedCamp.Landing_Page_URL__c, parentcamp.Landing_Page_URL__c);
    System.assertEquals(selectedCamp.Primary_Department__c, parentcamp.Primary_Department__c);
    System.assertEquals(selectedCamp.Primary_GAU__c, parentcamp.Primary_GAU__c);
    System.assertEquals(selectedCamp.Default_Letter_Code__c, parentcamp.Default_Letter_Code__c);
    System.assertEquals(selectedCamp.Default_Market_Code__c, parentcamp.Default_Market_Code__c);
    System.assertEquals(selectedCamp.StartDate, parentcamp.StartDate);
    System.assertEquals(selectedCamp.EndDate, parentcamp.EndDate);
  }

  @isTest
  static void testAddCampaignMemberStatusItems() {
    Campaign camp = new Campaign();
    camp.name = 'camp';
    insert camp;
    List<CampaignMemberStatus> cmsList = [select id, Label from CampaignMemberStatus where CampaignId =: camp.id];
    System.assertEquals(4, cmsList.size());
    Set<String> statusSet = new Set<String>();
    for (CampaignMemberStatus cms : cmsList) {
      statusSet.add(cms.Label);
    }
    System.assertEquals(true, statusSet.contains('Invited'));
    System.assertEquals(true, statusSet.contains('Attending'));
    System.assertEquals(true, statusSet.contains('Attended'));
    System.assertEquals(true, statusSet.contains('Absent'));
  }

  @isTest
  static void testSetStartEndDate() {
    Campaign camp = new Campaign();
    camp.name = 'camp';
    camp.Start_Time__c = DateTime.newInstance(2016, 8, 3);
    camp.End_Time__c = DateTime.newInstance(2016, 8, 4);
    insert camp;

    Campaign selectedCamp = [Select StartDate, EndDate, Primary_Department__c from campaign where id =: camp.id][0];
    System.assertEquals(selectedCamp.StartDate.year(), 2016);
    System.assertEquals(selectedCamp.EndDate.year(), 2016);
    System.assertEquals(selectedCamp.StartDate.month(), 8);
    System.assertEquals(selectedCamp.EndDate.month(), 8);
    System.assertEquals(selectedCamp.StartDate.day(), 3);
    System.assertEquals(selectedCamp.EndDate.day(), 4);
  }
}