objects/Campaign.object
<CustomObject><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Location_Address__c</fullName>
        <inlineHelpText>Address for the Event</inlineHelpText>
        <label>Location Address</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <inlineHelpText>City, State</inlineHelpText>
        <label>Location City, State</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><sharingModel>FullAccess</sharingModel><recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>An event where people come together</description>
        <label>Event</label>
    </recordTypes><recordTypes>
        <fullName>List</fullName>
        <active>true</active>
        <label>List</label>
    </recordTypes></CustomObject>

classes/EventsByDate_Controller.cls
global with sharing class EventsByDate_Controller {
  @AuraEnabled
  public static List<Campaign> getEventDetails() {
    return [SELECT
            ID,
            Name,
            StartDate,
            EndDate,
            Location__c,
            Location_Address__c,
            Start_Time__c,
            End_Time__c
            FROM Campaign
            WHERE isactive=true
            AND RecordType.Name='Event'
            AND EndDate >= TODAY
            ORDER BY StartDate ASC];
  }

  @RemoteAction
  global static List<Campaign> getEvents() {
    return [SELECT
            ID,
            Name,
            StartDate,
            EndDate,
            Location__c,
            Location_Address__c,
            Start_Time__c,
            End_Time__c
            FROM Campaign
            WHERE isactive=true
            AND RecordType.Name='Event'
            AND EndDate >= TODAY
            ORDER BY StartDate ASC];
  }
}