objects/Campaign.object
<CustomObject><fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Description_Rich__c</fullName>
        <inlineHelpText>Use the "Bold" as a sub heading</inlineHelpText>
        <label>Description_Rich</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Landing_Page_URL__c</fullName>
        <label>Landing Page URL</label>
        <type>Url</type>
    </fields><fields>
        <fullName>Location_Address__c</fullName>
        <inlineHelpText>Address for the Event</inlineHelpText>
        <label>Location Address</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <inlineHelpText>City, State</inlineHelpText>
        <label>Location City, State</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Event's Primary Contact</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>State__c</fullName>
        <label>State / Province</label>
        <picklist>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><sharingModel>FullAccess</sharingModel><recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>An event where people come together</description>
        <label>Event</label>
    </recordTypes><recordTypes>
        <fullName>List</fullName>
        <active>true</active>
        <label>List</label>
    </recordTypes></CustomObject>

classes/EventsController.cls
global without sharing class EventsController {

  @RemoteAction
  global static List<Campaign> getEvents(Integer month, Integer year, String state) {
    Integer numDays = Date.daysInMonth(year, month);
    Datetime beginningDate = Datetime.newInstance(year, month, 1, 0, 0, 0);
    Datetime endingDate = Datetime.newInstance(year, month, numDays, 23, 59, 59);
    String query = 'SELECT ' +
            'ID, ' +
            'Name, ' +
            'StartDate, ' +
            'EndDate, ' +
            'Location__c, ' +
            'City__c, ' +
            'State__c, ' +
            'Location_Address__c, ' +
            'Landing_Page_URL__c, ' +
            'Start_Time__c, ' +
            'End_Time__c ' +
            'FROM Campaign ' +
            'WHERE isactive=true ' +
              'AND RecordType.Name=\'Event\' ' +
              'AND Type != \'Expo\'' +
              'AND Start_Time__c >= :beginningDate ' +
              'AND Start_Time__c <= :endingDate ';
    if (!String.isEmpty(state)) {
      query = query + 'AND State__c = :state ';
    }
    query = query + 'ORDER BY StartDate ASC';
    return Database.query(query);
  }

  @RemoteAction
  global static Campaign getEventDetails(String eventId) {
    List<Campaign> campaignList = [SELECT ID,
                                   Name,
                                   StartDate,
                                   EndDate,
                                   Description_Rich__c,
                                   Location__c,
                                   City__c,
                                   State__c,
                                   Location_Address__c,
                                   Start_Time__c,
                                   End_Time__c,
                                   Primary_Contact__c,
                                   Primary_Contact__r.Phone,
                                   Primary_Contact__r.Email,
                                   Primary_Contact__r.FirstName,
                                   Primary_Contact__r.LastName FROM Campaign WHERE id = :eventId];
    return campaignList.isEmpty() ? null : campaignList[0];
  }
}