objects/Campaign.object
<CustomObject><fields>
        <fullName>Description_Rich__c</fullName>
        <inlineHelpText>Use the "Bold" as a sub heading</inlineHelpText>
        <label>Description_Rich</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Location_Address__c</fullName>
        <inlineHelpText>Address for the Event</inlineHelpText>
        <label>Location Address</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <inlineHelpText>City, State</inlineHelpText>
        <label>Location City, State</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Event's Primary Contact</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><sharingModel>FullAccess</sharingModel><recordTypes>
        <fullName>List</fullName>
        <active>true</active>
        <label>List</label>
    </recordTypes></CustomObject>

classes/EventDetails_Controller.cls
public with sharing class EventDetails_Controller {
  //@AuraEnabled
  //public static Campaign getEventDetails(String eventId) {
  //  List<Campaign> campaignList = [SELECT ID,
  //  Name,
  //  StartDate,
  //  EndDate,
  //  Description_Rich__c,
  //  Location__c,
  //  Location_Address__c,
  //  Featured_Image__c,
  //  Start_Time__c,
  //  End_Time__c,
  //  Primary_Contact__c,
  //  Primary_Contact__r.Phone,
  //  Primary_Contact__r.Email,
  //  Primary_Contact__r.FirstName,
  //  Primary_Contact__r.LastName FROM Campaign WHERE id = :eventId];
  //  return campaignList.isEmpty() ? null : campaignList[0];
  //}
}