objects/Campaign.object
<CustomObject><fields>
        <fullName>Default_Letter_Code__c</fullName>
        <label>Default Letter Code</label>
        <picklist>
            <picklistValues>
                <fullName>Calendar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada Sweepstakes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committee Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donation Calendar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ducks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Volunteer Raffle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Hunt Mem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Donation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gratis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hunters Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sportsman’s Raffle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spring Raffle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Truck Raffle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waterfowl ID Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>We do ours Seperate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Winter Raffle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Year End</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Default_Market_Code__c</fullName>
        <label>Default Market Code</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Landing_Page_URL__c</fullName>
        <label>Landing Page URL</label>
        <type>Url</type>
    </fields><fields>
        <fullName>Primary_Department__c</fullName>
        <globalPicklist>Departments</globalPicklist>
        <label>Primary Department</label>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Primary_GAU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary GAU</label>
        <referenceTo>npsp__General_Accounting_Unit__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><sharingModel>FullAccess</sharingModel><recordTypes>
        <fullName>List</fullName>
        <active>true</active>
        <label>List</label>
    </recordTypes><recordTypes>
        <fullName>Void</fullName>
        <active>false</active>
        <description>Tickets are sold to a group of people in order to win something</description>
        <label>Void</label>
    </recordTypes></CustomObject>

classes/CampaignService.cls
public with sharing class CampaignService {
// TODO: Tests
  public static void setParentDefaults(List<Campaign> campaigns) {
    Set<Id> parentIds = new Set<Id>();
    List<Campaign> filteredCampaigns = new List<Campaign>();
    for (Campaign camp : campaigns) {
      if (camp.parentId != null) {
        parentIds.add(camp.parentId);
        filteredCampaigns.add(camp);
      }
    }
    List<Campaign> parentCampaigns = [select id, Landing_Page_URL__c, Primary_Department__c, Primary_GAU__c, Default_Letter_Code__c, Default_Market_Code__c, StartDate, EndDate from Campaign where id in :parentIds];
    for (Campaign camp : filteredCampaigns) {
      for (Campaign parentCamp : parentCampaigns) {
        if (camp.ParentId == parentCamp.id) {
          if (camp.Landing_Page_URL__c == null) {
            camp.Landing_Page_URL__c = parentCamp.Landing_Page_URL__c;
          }
          if (camp.Primary_Department__c == null) {
            camp.Primary_Department__c = parentCamp.Primary_Department__c;
          }
          if (camp.Primary_GAU__c == null) {
            camp.Primary_GAU__c = parentCamp.Primary_GAU__c;
          }
          if (camp.Default_Letter_Code__c == null) {
            camp.Default_Letter_Code__c = parentCamp.Default_Letter_Code__c;
          }
          if (camp.Default_Market_Code__c == null) {
            camp.Default_Market_Code__c = parentCamp.Default_Market_Code__c;
          }
          if (camp.StartDate == null) {
            camp.StartDate = parentCamp.StartDate;
          }
          if (camp.EndDate == null) {
            camp.EndDate = parentCamp.EndDate;
          }
          break;
        }
      }
    }
  }

  public static void addCampaignMemberStatusItems(List<Campaign> campaigns) {
    List<String> statuses = new List<String> { 'Invited', 'Attending', 'Attended', 'Absent' };
    List<CampaignMemberStatus> cmsList = new List<CampaignMemberStatus>();
    for (Campaign camp : campaigns) {
      for(Integer i = 0; i < statuses.size(); i++) {
        String status = statuses[i];
        CampaignMemberStatus cms = new CampaignMemberStatus();
        cms.campaignId = camp.id;
        cms.HasResponded = status != 'Invited';
        cms.IsDefault = status == 'Invited';
        cms.Label = status;
        cms.SortOrder = i + 3;
        cmsList.add(cms);
      }
    }
    insert cmsList;
  }

  public static void setStartEndDate(List<Campaign> campaigns) {
    for(Campaign camp : campaigns) {
      if (camp.Start_Time__c != null) {
        camp.StartDate = Date.newinstance(camp.Start_Time__c.year(), camp.Start_Time__c.month(), camp.Start_Time__c.day());
      }
      if (camp.End_Time__c != null) {
        camp.EndDate = Date.newinstance(camp.End_Time__c.year(), camp.End_Time__c.month(), camp.End_Time__c.day());
      }
    }
  }
}