objects/Campaign.object
<CustomObject><fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Landing_Page_URL__c</fullName>
        <label>Landing Page URL</label>
        <type>Url</type>
    </fields><fields>
        <fullName>Location_Address__c</fullName>
        <inlineHelpText>Address for the Event</inlineHelpText>
        <label>Location Address</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>State__c</fullName>
        <label>State / Province</label>
        <picklist>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><sharingModel>FullAccess</sharingModel><recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>An event where people come together</description>
        <label>Event</label>
    </recordTypes><recordTypes>
        <fullName>List</fullName>
        <active>true</active>
        <label>List</label>
    </recordTypes><recordTypes>
        <fullName>Void</fullName>
        <active>false</active>
        <description>Tickets are sold to a group of people in order to win something</description>
        <label>Void</label>
    </recordTypes></CustomObject>

classes/EventsController_Test.cls
@isTest
private class EventsController_Test {
  @isTest
  static void testGetEvents() {

    Integer numDays = Date.daysInMonth(2016, 10);
    List<Campaign> testCampaignList = new List<Campaign>();

    // Event in current month
    Campaign testCampaign1 = new Campaign();
    testCampaign1.Name = 'testCampaign1';
    testCampaign1.isactive = true;
    testCampaign1.City__c = 'Annville';
    testCampaign1.State__c = 'MD';
    testCampaign1.Location_Address__c = '456 testAddress2';
    testCampaign1.Landing_Page_URL__c = 'www.testCampaign1.com';
    testCampaign1.RecordTypeID = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Event').getRecordTypeId();
    testCampaign1.Start_Time__c = Datetime.newInstance(2016, 10, 15, 12, 0, 0);
    testCampaign1.End_Time__c = Datetime.newInstance(2016, 10, 15, 17, 30, 0);

    // Another event in current month
    Campaign testCampaign2 = new Campaign();
    testCampaign2.Name = 'testCampaign2';
    testCampaign2.isactive = true;
    testCampaign2.City__c = 'Annville';
    testCampaign2.State__c = 'PA';
    testCampaign2.Location_Address__c = '456 testAddress3';
    testCampaign2.Landing_Page_URL__c = 'www.testCampaign2.com';
    testCampaign2.RecordTypeID = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Event').getRecordTypeId();
    testCampaign2.Start_Time__c = Datetime.newInstance(2016, 10, 20, 13, 0, 0);
    testCampaign2.End_Time__c = Datetime.newInstance(2016, 10, 20, 17, 30, 0);

    // Another event in current month
    Campaign testCampaign3 = new Campaign();
    testCampaign3.Name = 'testCampaign3';
    testCampaign3.isactive = true;
    testCampaign3.City__c = 'Annville';
    testCampaign3.State__c = 'NY';
    testCampaign3.Location_Address__c = '456 testAddress3';
    testCampaign3.Landing_Page_URL__c = 'www.testCampaign3.com';
    testCampaign3.RecordTypeID = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Event').getRecordTypeId();
    testCampaign3.Start_Time__c = Datetime.newInstance(2016, 11, 20, 13, 0, 0);
    testCampaign3.End_Time__c = Datetime.newInstance(2016, 11, 20, 17, 30, 0);

    insert testCampaign1;
    insert testCampaign2;
    insert testCampaign3;

    Test.StartTest();

    List<Campaign> eventList = EventsController.getEvents(10, 2016, null);
    System.assertEquals(2, eventList.size());

    eventList = EventsController.getEvents(10, 2016, 'PA');
    System.assertEquals(1, eventList.size());

    Test.StopTest();
  }
}