objects/Contact.object
<CustomObject><fields>
        <fullName>Auto_Membership_Id__c</fullName>
        <description>Do not modify this field</description>
        <label>Mem Id Gen</label>
        <type>AutoNumber</type>
    </fields><fields>
        <fullName>Membership_ID__c</fullName>
        <label>Membership ID</label>
        <length>30</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>Community_User_Compact_Layout</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/MembershipIdAssignment.cls
public class MembershipIdAssignment {

  @Future
  public static void addMembershipId(List<Id> conIds) {
    List<Contact> cons = [select id, Auto_Membership_Id__c from Contact where id in: conIds];
    for (Contact con : cons) {
      con.Membership_Id__c = (String)con.get('Auto_Membership_Id__c');
    }
    update cons;
  }

  @InvocableMethod
  public static void addMembershipIdInvocable(List<Id> conIds) {
    addMembershipId(conIds);
  }
}