objects/Opportunity.object
<CustomObject><fields>
        <fullName>Payment_Method__c</fullName>
        <globalPicklist>Payment_Method</globalPicklist>
        <label>Payment Method</label>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Web_Order_Number__c</fullName>
        <label>Web Order Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><recordTypes>
        <fullName>Donation</fullName>
        <active>true</active>
        <businessProcess>Delta Sales Process</businessProcess>
        <description>Donation Received</description>
        <label>Donation</label>
    </recordTypes><recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <businessProcess>Delta Sales Process</businessProcess>
        <description>A membership record type</description>
        <label>Membership</label>
    </recordTypes><recordTypes>
        <fullName>Merchandise</fullName>
        <active>true</active>
        <businessProcess>Delta Sales Process</businessProcess>
        <description>Store Items</description>
        <label>Merchandise</label>
    </recordTypes></CustomObject>

objects/WooCommerce_Serializer__c.object
<CustomObject><fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WooCommerce Serializers</relationshipLabel>
        <relationshipName>WooCommerce_Serializers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>WooCommerce Serializers</relationshipLabel>
        <relationshipName>WooCommerce_Serializers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Order_Number__c</fullName>
        <externalId>true</externalId>
        <label>Order Number</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>false</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>WooCommerce Serializer</label><nameField>
        <label>WooCommerce Serializer Name</label>
        <type>Text</type>
    </nameField><pluralLabel>WooCommerce Serializers</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/WooCommerceOrderBatcher_Test.cls
@isTest
private class WooCommerceOrderBatcher_Test {

  static WooCommerce_Serializer__c setup(Contact con, String body) {
    Account acc = new Account();
    acc.Name = 'Test';
    insert acc;
    con.AccountId = acc.id;
    insert con;
    WooCommerce_Serializer__c ws = new WooCommerce_Serializer__c(
      Account__c = acc.id,
      Contact__c = con.id,
      Order_Number__c = 1,
      Body__c = body,
      Status__c = 'Not Processed'
    );
    insert ws;
    return ws;
  }

  @isTest
  static void testBatcher() {
    WooCommerce_Test_Models wctm = new WooCommerce_Test_Models();
    WooCommerce_Serializer__c ws = setup(wctm.testContact, wctm.testOrder);
    WooCommerceOrderBatcher wob = new WooCommerceOrderBatcher();
    Test.StartTest();
    wob.execute((SchedulableContext)null);
    Test.StopTest();

    List<Opportunity> oppList = [SELECT Id, Amount, CampaignId, CloseDate, Payment_Method__c, StageName, Name, RecordType.Name FROM Opportunity WHERE Web_Order_Number__c = 1];
    Integer numDonationOpps = 0;
    Integer numMembershipOpps = 0;
    Integer numMerchandiseOpps = 0;
    Integer numTicketOpps = 0;
    for (Opportunity opp : oppList) {
      String recordtypename = opp.RecordType.Name;
      Opportunity compareOpp;
      if (recordtypename == 'Donation') {
        numDonationOpps++;
        compareOpp = wctm.oppForDonation;
      } else if (recordtypename == 'Membership') {
        numMembershipOpps++;
        compareOpp = wctm.oppForMembership;
      } else if (recordtypename == 'Merchandise') {
        numMerchandiseOpps++;
        compareOpp = wctm.oppForMerchandise;
      } else if (recordtypename == 'Ticket Order') {
        numTicketOpps++;
        compareOpp = wctm.oppForTicket;
      }
      System.assertEquals(compareOpp.Amount, opp.Amount);
      System.assertEquals(compareOpp.CampaignId, opp.CampaignId);
      System.assertEquals(compareOpp.CloseDate, opp.CloseDate);
      System.assertEquals(compareOpp.Name, opp.Name);
      System.assertEquals(compareOpp.Payment_Method__c, opp.Payment_Method__c);
      System.assertEquals(compareOpp.StageName, opp.StageName);
    }
    System.assertEquals(1, numDonationOpps);
    System.assertEquals(1, numMembershipOpps);
    System.assertEquals(1, numMerchandiseOpps);
    System.assertEquals(1, numTicketOpps);
  }

  @isTest
  static void testCadOrder() {
    WooCommerce_Test_Models wctm = new WooCommerce_Test_Models();
    WooCommerce_Serializer__c ws = setup(wctm.testContact, wctm.testCADOrder);
    WooCommerceOrderBatcher wob = new WooCommerceOrderBatcher();
    Test.StartTest();
    wob.execute((SchedulableContext)null);
    Test.StopTest();

    List<Opportunity> oppList = [SELECT Id, CurrencyIsoCode FROM Opportunity WHERE Web_Order_Number__c = 1];
    for (Opportunity opp : oppList) {
      system.assertEquals('CAD', opp.CurrencyIsoCode);
    }
  }
}