objects/Opportunity.object
<CustomObject><fields>
        <fullName>Payment_Method__c</fullName>
        <globalPicklist>Payment_Method</globalPicklist>
        <label>Payment Method</label>
        <type>Picklist</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><recordTypes>
        <fullName>Donation</fullName>
        <active>true</active>
        <businessProcess>Delta Sales Process</businessProcess>
        <description>Donation Received</description>
        <label>Donation</label>
    </recordTypes><recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <businessProcess>Delta Sales Process</businessProcess>
        <description>A membership record type</description>
        <label>Membership</label>
    </recordTypes><recordTypes>
        <fullName>Merchandise</fullName>
        <active>true</active>
        <businessProcess>Delta Sales Process</businessProcess>
        <description>Store Items</description>
        <label>Merchandise</label>
    </recordTypes></CustomObject>

objects/Transaction__c.object
<CustomObject><fields>
        <fullName>Payment_Method__c</fullName>
        <globalPicklist>Payment_Method</globalPicklist>
        <label>Payment Method</label>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>false</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>false</enableSharing><enableStreamingApi>false</enableStreamingApi><label>Transaction</label><nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Transactions</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/WooCommerce_Serializer__c.object
<CustomObject><fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WooCommerce Serializers</relationshipLabel>
        <relationshipName>WooCommerce_Serializers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>WooCommerce Serializers</relationshipLabel>
        <relationshipName>WooCommerce_Serializers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>WooCommerce Serializers</relationshipLabel>
        <relationshipName>WooCommerce_Serializers</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Order_Number__c</fullName>
        <externalId>true</externalId>
        <label>Order Number</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>false</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>WooCommerce Serializer</label><nameField>
        <label>WooCommerce Serializer Name</label>
        <type>Text</type>
    </nameField><pluralLabel>WooCommerce Serializers</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/WooCommerceOrderBatcher.cls
global with sharing class WooCommerceOrderBatcher implements Database.Batchable <sObject>, Schedulable {

  private Integer batchSize = 1;

  global WooCommerceOrderBatcher() {}

  global WooCommerceOrderBatcher(Integer batchSize) {
    this.batchSize = batchSize;
  }

  global void execute(SchedulableContext sc) {
    Database.executebatch(this, batchSize);
  }

  global Database.QueryLocator start(Database.BatchableContext BC) {
    return Database.getQueryLocator([Select Id, Contact__c, Account__c, Body__c, Order_Number__c from WooCommerce_Serializer__c where Status__c = 'Not Processed']);
  }

  global void execute(Database.BatchableContext BC, List <sObject> scope) {
    Savepoint sp = Database.setSavepoint();
    WooCommerce_Serializer__c ws = (WooCommerce_Serializer__c)scope[0];
    try {
      handler(ws);
      ws.Status__c = 'Processed';
    } catch (Exception ex) {
      Database.rollback(sp);
      ws.Status__c = 'Failed';
      ws.Error__c = ex.getMessage() + '/n/n' + ex.getStackTraceString();
    }
    update ws;
  }

  global void finish(Database.BatchableContext BC) {}

  private static void handler(WooCommerce_Serializer__c ws) {
    WooCommerceModel.WooCommercePayloadModel wcpm = (WooCommerceModel.WooCommercePayloadModel)JSON.deserialize(ws.Body__c, WooCommerceModel.WooCommercePayloadModel.class);
    List<WooCommerceModel.WooCommerceLineItem> donationLineItems = new List<WooCommerceModel.WooCommerceLineItem>();
    List<WooCommerceModel.WooCommerceLineItem> merchandiseLineItems = new List<WooCommerceModel.WooCommerceLineItem>();
    List<WooCommerceModel.WooCommerceLineItem> ticketLineItems = new List<WooCommerceModel.WooCommerceLineItem>();
    Decimal donationTotalSum = 0.0;
    Decimal merchandiseTotalSum = 0.0;
    Decimal ticketTotalSum = 0.0;
    Transaction__c tran = new Transaction__c();
    tran.Payment_Method__c = 'Credit Card';
    tran.ownerId = '00536000001teKUAAY';
    insert tran;

    List<Opportunity> oppList = new List<Opportunity>();
    for (WooCommerceModel.WooCommerceLineItem li : wcpm.order.line_items) {
      if (li.product_type != null && li.product_type.toLowerCase() == 'membership') {
        oppList.add(WooCommerceService.generateMembership(wcpm.order, li, ws.Account__c, tran.Id));
      } else if (li.product_type != null && li.product_type.toLowerCase() == 'donation') {
        donationTotalSum += li.total;
        donationLineItems.add(li);
      } else if (li.product_type != null && li.product_type.toLowerCase() == 'merchandise') {
        merchandiseTotalSum += li.total;
        merchandiseLineItems.add(li);
      } else if (li.product_type != null && li.product_type.toLowerCase() == 'ticket') {
        ticketTotalSum += li.total;
        ticketLineItems.add(li);
      }
    }

    Opportunity donationOpp;
    Opportunity merchandiseOpp;
    Opportunity ticketOpp;
    Id donationId;
    Id merchandiseId;
    Id ticketId;
    if (donationLineItems.size() != 0) {
      donationOpp = WooCommerceService.generateDonation(wcpm.order, ws.Account__c, donationTotalSum, tran.Id);
      donationId = donationOpp.id;
      oppList.add(donationOpp);
    }
    if (merchandiseLineItems.size() != 0) {
      merchandiseOpp = WooCommerceService.generateMerchandise(wcpm.order, ws.Account__c, merchandiseTotalSum, tran.Id);
      merchandiseId = merchandiseOpp.id;
      oppList.add(merchandiseOpp);
    }
    if (ticketLineItems.size() != 0) {
      ticketOpp = WooCommerceService.generateTicket(wcpm.order, ws.Account__c, ticketTotalSum, tran.Id);
      ticketId = ticketOpp.id;
      oppList.add(ticketOpp);
    }

    upsert oppList;

    if (donationId == null && donationOpp != null) {
      WooCommerceService.donationHandler(donationOpp, donationLineItems);
      ws.Opportunity__c = donationOpp.Id;
    }
    if (merchandiseId == null && merchandiseOpp != null) {
      WooCommerceService.merchandiseHandler(merchandiseOpp, merchandiseLineItems);
      ws.Opportunity__c = merchandiseOpp.Id;
    }
    if (ticketId == null && ticketOpp != null) {
      WooCommerceService.ticketHandler(ticketOpp, ticketLineItems);
      ws.Opportunity__c = ticketOpp.Id;
    }
  }
}