objects/Transaction__c.object
<CustomObject><fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Opportunity_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Opportunity Count</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>false</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>false</enableSharing><enableStreamingApi>false</enableStreamingApi><label>Transaction</label><nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Transactions</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/DeleteTransactionRecords_Test.cls
@isTest
private class DeleteTransactionRecords_Test {

	@isTest
	static void testDeleteTransactionRecords() {
		Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
		User u = new User(Alias = 'mytest', Email='candadmin@testorg.com',
		EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
		LocaleSidKey='en_US', ProfileId = p.Id,
		TimeZoneSidKey='America/Los_Angeles', UserName='candadmin@testorg.com');

		System.runAs(u) {
			List<Transaction__c> transList = new List<Transaction__c>();

			for (Integer i = 0; i < 5; i++) {
				Transaction__c t = new Transaction__c();
				t.Opportunity_Count__c = 0;
				t.Amount__c = 0.00;
				t.CurrencyIsoCode = 'USD';
				transList.add(t);
			}

			insert transList;

			Test.StartTest();
			DeleteTransactionRecords del = new DeleteTransactionRecords();
			Database.executeBatch(del);
			Test.StopTest();

		}
	}
}