objects/Transaction__c.object
<CustomObject><fields>
        <fullName>Opportunity_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Opportunity Count</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>false</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>false</enableSharing><enableStreamingApi>false</enableStreamingApi><label>Transaction</label><nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Transactions</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/DeleteTransactionRecords.cls
global class DeleteTransactionRecords implements Database.Batchable <sObject>, Schedulable {

  public List<Transaction__c> transList = [SELECT Id FROM Transaction__c WHERE Opportunity_Count__c = 0];
	public class applicationException extends Exception {}

  global void execute(SchedulableContext sc) {
    Database.executebatch(this);
  }

  global List<Transaction__c> start(Database.BatchableContext BC) {
    return transList;
  }

  global void execute(Database.BatchableContext BC, List <Transaction__c> scope) {
		delete scope;
  }

  global void finish(Database.BatchableContext BC) {
  }
}